name: Generate Pacman Animation

on:
  # Menjadwalkan eksekusi setiap 12 jam
  schedule:
    - cron: '0 */12 * * *'  # Setiap jam 00 dan 12

  # Memungkinkan eksekusi manual melalui GitHub UI
  workflow_dispatch:

  # Men-trigger workflow saat ada push ke branch main
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate & Deploy SVG
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write  # Diperlukan untuk push ke repository

    steps:
      # Step 1: Generate pacman-contribution-graph.svg
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Step 2: Deploy SVG ke branch `output`
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
